# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Status.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Status.proto',
  package='rs',
  serialized_pb='\n\x0cStatus.proto\x12\x08rs\"\xf5\x02\n\x06Status\x12/\n\x11\x63urrentSystemMode\x18\x01 \x02(\x0e\x32\x14.rs.SystemMode\x12\x1c\n\x14vehicleBatteryHealth\x18\x02 \x02(\x05\x12\x1a\n\x12vehicleClampStatus\x18\x03 \x02(\x08\x12:\n\x13vehicleCameraStatus\x18\x04 \x02(\x0e\x32\x1d.rs.VehicleCameraStatus\x12\x1f\n\x17manipulatorMagnetStatus\x18\x05 \x02(\x08\x12$\n\x1cmanipulatorMagnetLatchStatus\x18\x06 \x02(\x08\x12!\n\x19layerThicknessMeasurement\x18\x07 \x02(\x05\x12 \n\x18vehiclePositionAlongRail\x18\x08 \x02(\x05\x12\x14\n\x0cvehicleSpeed\x18\t \x02(\x05\x12\"\n\x07\x65rrorId\x18\n \x02(\x0e\x32\x11.rs.ErrorID*E\n\nSystemMode\x12\x0b\n\x07Vehicle\x10\x01\x12\x14\n\x10LargeManipulator\x10\x02\x12\x14\n\x10SmallManipulator\x10\x03*;\n\x13VehicleCameraStatus\x12\x08\n\x04Stow\x10\x01\x12\x0b\n\x07\x46orward\x10\x02\x12\r\n\tPanoramic\x10\x03*j\n\x07\x45rrorID\x12\x08\n\x04None\x10\x01\x12\x0b\n\x07Low_bat\x10\x02\x12\t\n\x05\x43lamp\x10\x03\x12\n\n\x06Magnet\x10\x04\x12\x0e\n\nConnection\x10\x05\x12\x14\n\x10State_infeasible\x10\x06\x12\x0b\n\x07Unknown\x10\x07')

_SYSTEMMODE = _descriptor.EnumDescriptor(
  name='SystemMode',
  full_name='rs.SystemMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Vehicle', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LargeManipulator', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SmallManipulator', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=402,
  serialized_end=471,
)

SystemMode = enum_type_wrapper.EnumTypeWrapper(_SYSTEMMODE)
_VEHICLECAMERASTATUS = _descriptor.EnumDescriptor(
  name='VehicleCameraStatus',
  full_name='rs.VehicleCameraStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Stow', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Forward', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Panoramic', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=473,
  serialized_end=532,
)

VehicleCameraStatus = enum_type_wrapper.EnumTypeWrapper(_VEHICLECAMERASTATUS)
_ERRORID = _descriptor.EnumDescriptor(
  name='ErrorID',
  full_name='rs.ErrorID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Low_bat', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Clamp', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Magnet', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Connection', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='State_infeasible', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=6, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=534,
  serialized_end=640,
)

ErrorID = enum_type_wrapper.EnumTypeWrapper(_ERRORID)
Vehicle = 1
LargeManipulator = 2
SmallManipulator = 3
Stow = 1
Forward = 2
Panoramic = 3
NoError = 1
Low_bat = 2
Clamp = 3
Magnet = 4
Connection = 5
State_infeasible = 6
Unknown = 7



_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='rs.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentSystemMode', full_name='rs.Status.currentSystemMode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicleBatteryHealth', full_name='rs.Status.vehicleBatteryHealth', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicleClampStatus', full_name='rs.Status.vehicleClampStatus', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicleCameraStatus', full_name='rs.Status.vehicleCameraStatus', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='manipulatorMagnetStatus', full_name='rs.Status.manipulatorMagnetStatus', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='manipulatorMagnetLatchStatus', full_name='rs.Status.manipulatorMagnetLatchStatus', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layerThicknessMeasurement', full_name='rs.Status.layerThicknessMeasurement', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehiclePositionAlongRail', full_name='rs.Status.vehiclePositionAlongRail', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicleSpeed', full_name='rs.Status.vehicleSpeed', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorId', full_name='rs.Status.errorId', index=9,
      number=10, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=400,
)

_STATUS.fields_by_name['currentSystemMode'].enum_type = _SYSTEMMODE
_STATUS.fields_by_name['vehicleCameraStatus'].enum_type = _VEHICLECAMERASTATUS
_STATUS.fields_by_name['errorId'].enum_type = _ERRORID
DESCRIPTOR.message_types_by_name['Status'] = _STATUS

class Status(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATUS

  # @@protoc_insertion_point(class_scope:rs.Status)


# @@protoc_insertion_point(module_scope)
