# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VehicleOrientation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VehicleOrientation.proto',
  package='rs',
  serialized_pb='\n\x18VehicleOrientation.proto\x12\x08rs\"\xd1\x01\n\x12VehicleOrientation\x12\x19\n\x11manipulator1Angle\x18\x01 \x02(\x05\x12\x19\n\x11manipulator2Angle\x18\x02 \x02(\x05\x12\x19\n\x11manipulator3Angle\x18\x03 \x02(\x05\x12\x19\n\x11manipulator4Angle\x18\x04 \x02(\x05\x12\x19\n\x11manipulator5Angle\x18\x05 \x02(\x05\x12\x19\n\x11manipulator6Angle\x18\x06 \x02(\x05\x12\x19\n\x11manipulator7Angle\x18\x07 \x02(\x05')




_VEHICLEORIENTATION = _descriptor.Descriptor(
  name='VehicleOrientation',
  full_name='rs.VehicleOrientation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='manipulator1Angle', full_name='rs.VehicleOrientation.manipulator1Angle', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='manipulator2Angle', full_name='rs.VehicleOrientation.manipulator2Angle', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='manipulator3Angle', full_name='rs.VehicleOrientation.manipulator3Angle', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='manipulator4Angle', full_name='rs.VehicleOrientation.manipulator4Angle', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='manipulator5Angle', full_name='rs.VehicleOrientation.manipulator5Angle', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='manipulator6Angle', full_name='rs.VehicleOrientation.manipulator6Angle', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='manipulator7Angle', full_name='rs.VehicleOrientation.manipulator7Angle', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=248,
)

DESCRIPTOR.message_types_by_name['VehicleOrientation'] = _VEHICLEORIENTATION

class VehicleOrientation(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VEHICLEORIENTATION

  # @@protoc_insertion_point(class_scope:rs.VehicleOrientation)


# @@protoc_insertion_point(module_scope)
